[package]
name = "yagc"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
nom = "8.0.0"
rustls = "0.23.27"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.9"
tokio = { version = "1.45.1", features = ["full"] }
tokio-rustls = "0.26.2"
